---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
    purpose: efk-stack
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    name: apps
    purpose: demo-applications
